// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqzkxcutpxptcoycuyhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxemt4Y3V0cHhwdGNveWN1eWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzg0NjgsImV4cCI6MjA2NjgxNDQ2OH0.zKnYh34FUY1kzPQlbvxHhL2qJrQ38g99sjowUjBan_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});